import type { Metadata } from "next";
import "./globals.css"; //TAILWIND CSS IS ADDED BY THIS
import TheNavbar from "@/components/TheNavbar";
import TheFooter from "@/components/TheFooter";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import BasicApiCalls from "@/components/BasicApiCalls";

export const metadata: Metadata = {
  title: "AR7Eats",
  description: "Generated by create next app",
  authors: [{ name: "Apurbo Roy", url: "https://apurboroy7077.netlify.app" }],
  icons: { icon: ["/favicon.ico/v=4"] },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="" href="/images/icons/chicken.svg"></link>
      </head>
      <body>
        <ToastContainer />
        <BasicApiCalls />
        <header>
          <TheNavbar />
        </header>
        <main className=" min-h-[60vh]">{children}</main>
        <TheFooter />
      </body>
    </html>
  );
}
