import type { Metadata } from "next";
import "./globals.css"; //TAILWIND CSS IS ADDED BY THIS
import TheNavbar from "@/components/TheNavbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <TheNavbar />
        </header>
        {children}
      </body>
    </html>
  );
}
